version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    container_name: app_nginx
    depends_on:
      - php

  php:
    build:
      context: .
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9000:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: app_db

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
    container_name: phpmyadmin